[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
